name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: first docker build test
      run: docker build -t ${{ github.repository }}:${{ github.sha }} -f path/to/Dockerfile .
