name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
              username: ${{secrets.DOCKERHUB_USERNAME}}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build image
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:$COMMIT_SHA -f path/to/Dockerfile .

      - name: push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:$COMMIT_SHA


 
